
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: 1133
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

image:
  get:
    url: http:/localhost:8080/api/v1/picture/
server:
  upload:
    url : D:/Anvarbekov/spring/picture
